'use client';

import { useEffect, useState, useCallback, useRef } from 'react';
import { useTranslations } from 'next-intl';
import { useList } from '@/lib/hooks/useList';
import { useAI, ManipulatedItem } from '@/lib/hooks/useAI';
import { supabase } from '@/lib/supabase';
import { ListTitle } from '@/components/ListTitle';
import { ListContainer } from '@/components/ListContainer';
import { DictateButton } from '@/components/DictateButton';
import { SmartAppBanner } from '@/components/SmartAppBanner';
import { isCategorizedResult } from '@/lib/hooks/useAI';
import { ThemeColors } from '@/lib/gemini';
import { analytics } from '@/lib/analytics';
import { generateListId } from '@/lib/utils/generateId';
import { LanguageSwitcherCompact } from '@/components/LanguageSwitcher';
import { SaveAsTemplateModal } from '@/components/templates/SaveAsTemplateModal';

interface ListPageClientProps {
  listId: string;
}

export default function ListPageClient({ listId }: ListPageClientProps) {
  const t = useTranslations('list');
  const tCommon = useTranslations('common');

  const [copied, setCopied] = useState(false);
  const [copiedMarkdown, setCopiedMarkdown] = useState(false);
  const [showShareView, setShowShareView] = useState(false);
  const [showTemplateModal, setShowTemplateModal] = useState(false);
  const [isTitleAutoGenerated, setIsTitleAutoGenerated] = useState(false);
  const autoTitleTimeoutRef = useRef<NodeJS.Timeout | null>(null);
  const hasAutoGeneratedRef = useRef(false);

  const {
    list,
    items,
    itemTree,
    loading,
    error,
    newItemId,
    newItemIds,
    completingItemIds,
    createList,
    updateTitle,
    updateTheme,
    updateLargeMode,
    addItem,
    addItems,
    updateItem,
    toggleItem,
    deleteItem,
    reorderItems,
    moveToGroup,
    moveToRoot,
    indentItem,
    outdentItem,
    completeAll,
    uncompleteAll,
    clearCompleted,
    sortItems,
    ungroupAll,
    nukeItems,
    toggleEmojifyMode,
  } = useList(listId);

  const { manipulateList, generateItems, processDictation } = useAI();

  // Track page visit
  useEffect(() => {
    analytics.pageVisit(`/${listId}`);
  }, [listId]);

  // Create list if it doesn't exist (for direct URL access)
  useEffect(() => {
    if (!loading && !list && !error) {
      createList();
    }
  }, [loading, list, error, createList]);

  // Auto-generate title after 3+ items with 2-second debounce
  useEffect(() => {
    // Clear any existing timeout
    if (autoTitleTimeoutRef.current) {
      clearTimeout(autoTitleTimeoutRef.current);
    }

    // Only trigger if:
    // 1. List exists and has no title
    // 2. Has 3 or more non-header items
    // 3. Haven't already auto-generated a title this session
    const nonHeaderItems = items.filter(item => !item.content.startsWith('#'));
    const shouldAutoGenerate =
      list &&
      !list.title &&
      nonHeaderItems.length >= 3 &&
      !hasAutoGeneratedRef.current;

    if (shouldAutoGenerate) {
      autoTitleTimeoutRef.current = setTimeout(async () => {
        try {
          const itemContents = items
            .filter(item => !item.completed && !item.content.startsWith('#'))
            .map(item => item.content);

          if (itemContents.length === 0) return;

          const response = await fetch('/api/title', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ items: itemContents }),
          });

          if (response.ok) {
            const { title } = await response.json();
            // Only update if title is still null (user hasn't set one manually)
            if (!list.title) {
              hasAutoGeneratedRef.current = true;
              setIsTitleAutoGenerated(true);
              await updateTitle(title);
              // Reset the auto-generated flag after animation
              setTimeout(() => setIsTitleAutoGenerated(false), 1500);
            }
          }
        } catch (err) {
          console.error('Auto-title generation failed:', err);
        }
      }, 2000); // 2-second debounce
    }

    return () => {
      if (autoTitleTimeoutRef.current) {
        clearTimeout(autoTitleTimeoutRef.current);
      }
    };
  }, [items, list, updateTitle]);

  // Apply theme from list data
  const applyTheme = useCallback((theme: ThemeColors | null) => {
    const root = document.documentElement;
    if (theme) {
      root.style.setProperty('--primary', theme.primary);
      root.style.setProperty('--primary-dark', theme.primaryDark);
      root.style.setProperty('--primary-light', theme.primaryLight);
      root.style.setProperty('--primary-pale', theme.primaryPale);
      root.style.setProperty('--primary-glow', theme.primaryGlow);
      root.style.setProperty('--text-primary', theme.textPrimary);
      root.style.setProperty('--text-secondary', theme.textSecondary);
      root.style.setProperty('--text-muted', theme.textMuted);
      root.style.setProperty('--text-placeholder', theme.textPlaceholder);
      root.style.setProperty('--bg-primary', theme.bgPrimary);
      root.style.setProperty('--bg-secondary', theme.bgSecondary);
      root.style.setProperty('--bg-hover', theme.bgHover);
      root.style.setProperty('--border-light', theme.borderLight);
      root.style.setProperty('--border-medium', theme.borderMedium);
      root.style.setProperty('--error', theme.error);
    } else {
      // Reset to defaults
      root.style.removeProperty('--primary');
      root.style.removeProperty('--primary-dark');
      root.style.removeProperty('--primary-light');
      root.style.removeProperty('--primary-pale');
      root.style.removeProperty('--primary-glow');
      root.style.removeProperty('--text-primary');
      root.style.removeProperty('--text-secondary');
      root.style.removeProperty('--text-muted');
      root.style.removeProperty('--text-placeholder');
      root.style.removeProperty('--bg-primary');
      root.style.removeProperty('--bg-secondary');
      root.style.removeProperty('--bg-hover');
      root.style.removeProperty('--border-light');
      root.style.removeProperty('--border-medium');
      root.style.removeProperty('--error');
    }
  }, []);

  // Apply theme when list loads
  useEffect(() => {
    if (list) {
      applyTheme(list.theme);
    }
    // Cleanup: reset theme when leaving the page
    return () => {
      applyTheme(null);
    };
  }, [list, applyTheme]);

  // Handle theme generation
  const handleThemeGenerate = async (description: string) => {
    const response = await fetch('/api/theme', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ description }),
    });

    if (!response.ok) {
      const data = await response.json();
      throw new Error(data.error || 'Theme generation failed');
    }

    const { theme } = await response.json();

    // Apply theme immediately
    applyTheme(theme);

    // Save to database
    await updateTheme(theme);
  };

  // Handle theme reset
  const handleThemeReset = async () => {
    applyTheme(null);
    await updateTheme(null);
  };

  // Helper to emojify text
  const emojifyText = async (text: string): Promise<string> => {
    try {
      const response = await fetch('/api/emojify', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text }),
      });
      if (response.ok) {
        const { emoji } = await response.json();
        return `${emoji} ${text}`;
      }
    } catch (err) {
      console.error('Emojify failed:', err);
    }
    return text; // Return original if emojify fails
  };

  // Wrapper for addItem that handles emojify
  const handleAddItem = async (content: string, parentId?: string | null) => {
    let finalContent = content;
    // Only emojify regular items (not headers starting with #)
    if (list?.emojify_mode && !content.startsWith('#') && !content.startsWith('--')) {
      finalContent = await emojifyText(content);
    }
    await addItem(finalContent, parentId);
  };

  // Wrapper for addItems that handles emojify
  const handleAddItems = async (contents: string[], parentId?: string | null) => {
    let finalContents = contents;
    if (list?.emojify_mode) {
      // Emojify all items in parallel
      finalContents = await Promise.all(
        contents.map(async (content) => {
          if (!content.startsWith('#') && !content.startsWith('--')) {
            return await emojifyText(content);
          }
          return content;
        })
      );
    }
    return await addItems(finalContents, parentId);
  };

  const handleShareClick = () => {
    setShowShareView(true);
  };

  const handleCopyUrl = async () => {
    await navigator.clipboard.writeText(window.location.href);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleCopyMarkdown = async () => {
    // Convert list to Markdown format
    const title = list?.title || 'Untitled List';
    let markdown = `# ${title}\n\n`;

    // Group items by parent
    const rootItems = items.filter(item => !item.parent_id);
    const childrenByParent: Record<string, typeof items> = {};
    items.forEach(item => {
      if (item.parent_id) {
        if (!childrenByParent[item.parent_id]) {
          childrenByParent[item.parent_id] = [];
        }
        childrenByParent[item.parent_id].push(item);
      }
    });

    rootItems.forEach(item => {
      if (item.content.startsWith('#')) {
        // Header/category
        markdown += `## ${item.content.slice(1).trim()}\n`;
        const children = childrenByParent[item.id] || [];
        children.forEach(child => {
          const checkbox = child.completed ? '[x]' : '[ ]';
          markdown += `- ${checkbox} ${child.content}\n`;
        });
        markdown += '\n';
      } else {
        // Regular item
        const checkbox = item.completed ? '[x]' : '[ ]';
        markdown += `- ${checkbox} ${item.content}\n`;
      }
    });

    await navigator.clipboard.writeText(markdown.trim());
    setCopiedMarkdown(true);
    setTimeout(() => setCopiedMarkdown(false), 2000);
  };

  const handleDownloadTodoistCSV = () => {
    const title = list?.title || 'Listo List';

    // Todoist CSV format headers
    const headers = ['TYPE', 'CONTENT', 'DESCRIPTION', 'PRIORITY', 'INDENT', 'AUTHOR', 'RESPONSIBLE', 'DATE', 'DATE_LANG', 'TIMEZONE'];

    // Build CSV rows in Todoist format
    const rows: string[] = [];

    // List title as the parent task (indent 1), bold
    const escapedTitle = title.replace(/"/g, '""');
    rows.push(`task,"**${escapedTitle}**",,4,1,,,,,`);

    // Get root items
    const rootItems = items.filter(item => !item.parent_id);

    rootItems.forEach(item => {
      if (item.content.startsWith('#')) {
        // Category becomes a subtask (indent 2), bold for visibility
        const categoryName = item.content.slice(1).trim().replace(/"/g, '""');
        rows.push(`task,"**${categoryName}**",,4,2,,,,,`);

        // Items under category become indent 3
        const children = items.filter(child => child.parent_id === item.id && !child.completed);
        children.forEach(child => {
          const isNote = child.content.toLowerCase().startsWith('note:');
          if (isNote) {
            // Export as Todoist note type
            const noteContent = child.content.slice(5).trim().replace(/"/g, '""');
            rows.push(`note,"${noteContent}",,4,3,,,,,`);
          } else {
            const taskContent = child.content.replace(/"/g, '""');
            rows.push(`task,"${taskContent}",,4,3,,,,,`);
          }
        });
      } else if (item.content.toLowerCase().startsWith('note:')) {
        // Note at root level
        const noteContent = item.content.slice(5).trim().replace(/"/g, '""');
        rows.push(`note,"${noteContent}",,4,2,,,,,`);
      } else if (!item.completed) {
        // Regular task at indent 2 (under list title)
        const taskContent = item.content.replace(/"/g, '""');
        rows.push(`task,"${taskContent}",,4,2,,,,,`);
      }
    });

    const csv = [headers.join(','), ...rows].join('\n');

    // Create and trigger download
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${title.replace(/[^a-z0-9]/gi, '_')}_todoist.csv`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleBackToList = () => {
    setShowShareView(false);
    setCopied(false);
    setCopiedMarkdown(false);
  };

  // Handle Escape key to close share view
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && showShareView) {
        handleBackToList();
      }
    };
    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  }, [showShareView]);

  // Generate title from items
  const handleGenerateTitle = async () => {
    const itemContents = items
      .filter(item => !item.completed && !item.content.startsWith('#'))
      .map(item => item.content);

    if (itemContents.length === 0) return;

    try {
      const response = await fetch('/api/title', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ items: itemContents }),
      });

      if (response.ok) {
        const { title } = await response.json();
        await updateTitle(title);
      }
    } catch (err) {
      console.error('Title generation failed:', err);
    }
  };

  const handleManipulateList = async (instruction: string) => {
    // Get only incomplete items for manipulation
    const incompleteItems = items.filter(item => !item.completed);

    if (incompleteItems.length === 0) {
      throw new Error('No items to reorganize');
    }

    // Send to AI for manipulation
    const manipulatedItems = await manipulateList(incompleteItems, instruction);

    // Separate new items (headers) from existing items
    const newItems = manipulatedItems.filter(item => item.id.startsWith('new_'));
    const existingItems = manipulatedItems.filter(item => !item.id.startsWith('new_'));

    // Create a mapping from placeholder IDs to real IDs
    const idMapping: Record<string, string> = {};

    // Create new header items in database
    for (const newItem of newItems) {
      const { data, error } = await supabase
        .from('items')
        .insert({
          list_id: listId,
          content: newItem.content,
          completed: false,
          parent_id: null,
          position: newItem.position,
        })
        .select()
        .single();

      if (error) throw error;
      if (data) {
        idMapping[newItem.id] = data.id;
      }
    }

    // Update existing items with new positions and parent_ids
    for (const manipulatedItem of existingItems) {
      // Translate parent_id from placeholder to real ID
      let realParentId = manipulatedItem.parent_id;
      if (realParentId && idMapping[realParentId]) {
        realParentId = idMapping[realParentId];
      }

      await updateItem(manipulatedItem.id, {
        content: manipulatedItem.content,
        position: manipulatedItem.position,
        parent_id: realParentId,
      });
    }
  };

  // Handle dictation transcription - send to Gemini for list generation
  const handleDictation = async (transcription: string) => {
    if (!transcription.trim()) return;

    try {
      console.log('[List] Processing dictation:', transcription);
      const { title, titleCommand, items } = await processDictation(transcription);
      console.log('[List] Dictation result:', { title, titleCommand, itemCount: items.length });

      // Set title if it's a title command OR if list doesn't have a title yet
      if (title && (titleCommand || !list?.title)) {
        await updateTitle(title);
      }

      if (items.length > 0) {
        if (isCategorizedResult(items)) {
          await handleCategorizedGenerate(items);
        } else {
          // Simple string array - use bulk add
          await addItems(items as string[]);
        }
      }
    } catch (err) {
      console.error('Failed to process dictation:', err);
    }
  };

  // Handle AI-generated categorized items (all items are new)
  const handleCategorizedGenerate = async (generatedItems: ManipulatedItem[]) => {
    if (generatedItems.length === 0) return;

    // Create a mapping from placeholder IDs to real IDs
    const idMapping: Record<string, string> = {};

    // First pass: create all headers (items without parent_id)
    const headers = generatedItems.filter(item => !item.parent_id);
    for (const header of headers) {
      const { data, error } = await supabase
        .from('items')
        .insert({
          list_id: listId,
          content: header.content,
          completed: false,
          parent_id: null,
          position: header.position,
        })
        .select()
        .single();

      if (error) throw error;
      if (data) {
        idMapping[header.id] = data.id;
      }
    }

    // Second pass: create child items with translated parent_ids
    const children = generatedItems.filter(item => item.parent_id);
    for (const child of children) {
      // Translate parent_id from placeholder to real ID
      const realParentId = child.parent_id ? idMapping[child.parent_id] : null;

      const { data, error } = await supabase
        .from('items')
        .insert({
          list_id: listId,
          content: child.content,
          completed: false,
          parent_id: realParentId,
          position: child.position,
        })
        .select()
        .single();

      if (error) throw error;
      if (data) {
        idMapping[child.id] = data.id;
      }
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center" style={{ backgroundColor: 'var(--bg-primary)' }}>
        <div className="text-[var(--primary)] animate-pulse">{tCommon('loading')}</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen flex items-center justify-center" style={{ backgroundColor: 'var(--bg-primary)' }}>
        <div style={{ color: 'var(--error)' }}>{error}</div>
      </div>
    );
  }

  return (
    <div className="min-h-screen flex flex-col items-center" style={{ backgroundColor: 'var(--bg-primary)' }}>
      {/* Smart App Banner for iOS */}
      <SmartAppBanner listId={listId} listTitle={list?.title || null} />

      {/* Sticky Header */}
      <div
        className="flex justify-center"
        style={{
          position: 'sticky',
          top: 0,
          width: '100%',
          zIndex: 20,
          backgroundColor: 'var(--bg-primary)',
          paddingTop: 'max(16px, env(safe-area-inset-top))',
        }}
      >
        <div className="w-full max-w-lg" style={{ paddingLeft: '8px', paddingRight: '8px' }}>
          <div className="flex items-center justify-between" style={{ height: '44px' }}>
            <ListTitle title={list?.title || null} onUpdate={updateTitle} isAutoGenerated={isTitleAutoGenerated} />
            {showShareView ? (
              <button
                onClick={handleBackToList}
                className="text-sm py-1.5 transition-all duration-200 flex items-center gap-1.5 hover:text-[var(--primary)] hover:bg-[var(--primary-pale)] active:opacity-60"
                style={{
                  paddingLeft: '8px',
                  paddingRight: '8px',
                  borderRadius: '4px',
                  color: 'var(--text-muted)'
                }}
              >
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
                </svg>
                {t('backToList')}
              </button>
            ) : (
              <button
                onClick={handleShareClick}
                className="text-sm py-1.5 transition-all duration-200 flex items-center gap-1.5 hover:text-[var(--primary)] hover:bg-[var(--primary-pale)] active:opacity-60"
                style={{
                  paddingLeft: '8px',
                  paddingRight: '8px',
                  borderRadius: '4px',
                  color: 'var(--text-muted)'
                }}
              >
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" />
                </svg>
                {t('share.title')}
              </button>
            )}
          </div>
        </div>
      </div>

      {/* Centered content container */}
      <div className="w-full max-w-lg mx-auto pb-16" style={{ paddingLeft: '8px', paddingRight: '8px' }}>

        {/* Share View */}
        {showShareView ? (
          <div style={{ paddingTop: '16px' }}>
            {/* Collaboration explainer */}
            <div
              className="text-sm px-4"
              style={{ color: 'var(--text-muted)', marginBottom: '16px' }}
            >
              {t('share.instruction')}
            </div>

            {/* Share options - styled like list items */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
              {/* Copy URL */}
              <button
                onClick={handleCopyUrl}
                className="w-full flex items-center gap-3 py-3 px-4 rounded transition-all duration-150"
                style={{
                  backgroundColor: copied ? 'var(--primary-pale)' : 'transparent',
                }}
                onMouseEnter={(e) => { if (!copied) e.currentTarget.style.backgroundColor = 'var(--primary-pale)'; }}
                onMouseLeave={(e) => { if (!copied) e.currentTarget.style.backgroundColor = 'transparent'; }}
              >
                {copied ? (
                  <svg className="w-5 h-5 flex-shrink-0" style={{ color: 'var(--primary)' }} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                  </svg>
                ) : (
                  <svg className="w-5 h-5 flex-shrink-0" style={{ color: 'var(--text-muted)' }} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1" />
                  </svg>
                )}
                <span style={{ color: copied ? 'var(--primary)' : 'var(--text-primary)' }}>
                  {copied ? t('share.linkCopied') : t('share.copyLink')}
                </span>
              </button>

              {/* Copy as Markdown */}
              <button
                onClick={handleCopyMarkdown}
                className="w-full flex items-center gap-3 py-3 px-4 rounded transition-all duration-150"
                style={{
                  backgroundColor: copiedMarkdown ? 'var(--primary-pale)' : 'transparent',
                }}
                onMouseEnter={(e) => { if (!copiedMarkdown) e.currentTarget.style.backgroundColor = 'var(--primary-pale)'; }}
                onMouseLeave={(e) => { if (!copiedMarkdown) e.currentTarget.style.backgroundColor = 'transparent'; }}
              >
                {copiedMarkdown ? (
                  <svg className="w-5 h-5 flex-shrink-0" style={{ color: 'var(--primary)' }} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                  </svg>
                ) : (
                  <svg className="w-5 h-5 flex-shrink-0" style={{ color: 'var(--text-muted)' }} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                  </svg>
                )}
                <span style={{ color: copiedMarkdown ? 'var(--primary)' : 'var(--text-primary)' }}>
                  {copiedMarkdown ? t('share.markdownCopied') : t('share.copyMarkdown')}
                </span>
              </button>

              {/* Send via Email */}
              <a
                href={(() => {
                  const title = list?.title || 'Untitled List';
                  const subject = encodeURIComponent(`Here's a checklist for you: ${title}`);
                  const body = encodeURIComponent(`${title}\n\n${typeof window !== 'undefined' ? window.location.href : ''}`);
                  return `mailto:?subject=${subject}&body=${body}`;
                })()}
                className="w-full flex items-center gap-3 py-3 px-4 rounded transition-all duration-150"
                style={{ backgroundColor: 'transparent' }}
                onMouseEnter={(e) => { e.currentTarget.style.backgroundColor = 'var(--primary-pale)'; }}
                onMouseLeave={(e) => { e.currentTarget.style.backgroundColor = 'transparent'; }}
              >
                <svg className="w-5 h-5 flex-shrink-0" style={{ color: 'var(--text-muted)' }} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                </svg>
                <span style={{ color: 'var(--text-primary)' }}>
                  {t('share.sendEmail')}
                </span>
              </a>

              {/* Export for Todoist */}
              <div>
                <button
                  onClick={handleDownloadTodoistCSV}
                  className="w-full flex items-center gap-3 py-3 px-4 rounded transition-all duration-150"
                  style={{ backgroundColor: 'transparent' }}
                  onMouseEnter={(e) => { e.currentTarget.style.backgroundColor = 'var(--primary-pale)'; }}
                  onMouseLeave={(e) => { e.currentTarget.style.backgroundColor = 'transparent'; }}
                >
                  <svg className="w-5 h-5 flex-shrink-0" style={{ color: '#E44332' }} viewBox="0 0 24 24" fill="currentColor">
                    <path d="M21 0H3C1.35 0 0 1.35 0 3v18c0 1.65 1.35 3 3 3h18c1.65 0 3-1.35 3-3V3c0-1.65-1.35-3-3-3zM5.5 6.75h13c.414 0 .75.336.75.75s-.336.75-.75.75h-13c-.414 0-.75-.336-.75-.75s.336-.75.75-.75zm0 4.5h13c.414 0 .75.336.75.75s-.336.75-.75.75h-13c-.414 0-.75-.336-.75-.75s.336-.75.75-.75zm0 4.5h13c.414 0 .75.336.75.75s-.336.75-.75.75h-13c-.414 0-.75-.336-.75-.75s.336-.75.75-.75z"/>
                  </svg>
                  <span style={{ color: 'var(--text-primary)' }}>
                    {t('share.exportTodoist')}
                  </span>
                </button>
                <div className="text-xs px-4" style={{ color: 'var(--text-muted)', marginTop: '4px', marginLeft: '32px' }}>
                  {t('share.csvSubtitle')}
                </div>
              </div>

              {/* Save as Template */}
              {items.length > 0 && (
                <button
                  onClick={() => setShowTemplateModal(true)}
                  className="w-full flex items-center gap-3 py-3 px-4 rounded transition-all duration-150"
                  style={{ backgroundColor: 'transparent' }}
                  onMouseEnter={(e) => { e.currentTarget.style.backgroundColor = 'var(--primary-pale)'; }}
                  onMouseLeave={(e) => { e.currentTarget.style.backgroundColor = 'transparent'; }}
                >
                  <svg className="w-5 h-5 flex-shrink-0" style={{ color: 'var(--text-muted)' }} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7v8a2 2 0 002 2h6M8 7V5a2 2 0 012-2h4.586a1 1 0 01.707.293l4.414 4.414a1 1 0 01.293.707V15a2 2 0 01-2 2h-2M8 7H6a2 2 0 00-2 2v10a2 2 0 002 2h8a2 2 0 002-2v-2" />
                  </svg>
                  <span style={{ color: 'var(--text-primary)' }}>
                    {t('share.saveAsTemplate')}
                  </span>
                </button>
              )}
            </div>
          </div>
        ) : (
          /* List */
          <ListContainer
            items={itemTree}
            newItemId={newItemId}
            newItemIds={newItemIds}
            completingItemIds={completingItemIds}
            largeMode={list?.large_mode || false}
            onToggle={toggleItem}
            onUpdate={async (id, content) => {
              await updateItem(id, { content });
            }}
            onDelete={deleteItem}
            onIndent={indentItem}
            onOutdent={outdentItem}
            onReorder={async (activeId, overId) => {
              await reorderItems(activeId, overId);
            }}
            onMoveToGroup={moveToGroup}
            onMoveToRoot={moveToRoot}
            onAddItem={handleAddItem}
            onAddItems={handleAddItems}
            onManipulateList={handleManipulateList}
            onCategorizedGenerate={handleCategorizedGenerate}
            onThemeGenerate={handleThemeGenerate}
            onThemeReset={list?.theme ? handleThemeReset : undefined}
            onCompleteAll={completeAll}
            onUncompleteAll={uncompleteAll}
            onSetLargeMode={updateLargeMode}
            onClearCompleted={clearCompleted}
            onSort={sortItems}
            onUngroupAll={ungroupAll}
            onToggleEmojify={toggleEmojifyMode}
            onNuke={nukeItems}
            onGenerateTitle={handleGenerateTitle}
          />
        )}

        {/* Share hint - only show when not in share view */}
        {!showShareView && (
          <button
            onClick={() => setShowShareView(true)}
            className="text-center text-xs mt-6 w-full active:opacity-60 transition-opacity"
            style={{ color: 'var(--text-muted)', background: 'none', border: 'none', cursor: 'pointer' }}
          >
            {t('shareHint')}
          </button>
        )}

        {/* Footer - Created with Listo (hide when sharing) */}
        {!showShareView && (
          <div className="mt-12 mb-8 text-center" style={{ paddingBottom: '60px' }}>
            {/* Subtle divider */}
            <div
              style={{
                height: '1px',
                backgroundColor: 'var(--border-light)',
                opacity: 0.5,
                marginBottom: '24px',
              }}
            />

            <div className="text-xs" style={{ color: 'var(--text-muted)', marginBottom: '16px' }}>
              {t('footer.createdWith')}
            </div>

            <div className="flex items-center justify-center gap-4">
              <a
                href="/"
                className="text-sm font-medium transition-colors active:opacity-60"
                style={{ color: 'var(--primary)' }}
                onMouseEnter={(e) => e.currentTarget.style.color = 'var(--primary-dark)'}
                onMouseLeave={(e) => e.currentTarget.style.color = 'var(--primary)'}
              >
                {t('footer.home')}
              </a>
              <span style={{ color: 'var(--border-medium)' }}>·</span>
              <button
                onClick={() => {
                  const newListId = generateListId();
                  window.open(`/${newListId}`, '_blank');
                }}
                className="text-sm font-medium transition-colors active:opacity-60"
                style={{ color: 'var(--primary)' }}
                onMouseEnter={(e) => e.currentTarget.style.color = 'var(--primary-dark)'}
                onMouseLeave={(e) => e.currentTarget.style.color = 'var(--primary)'}
              >
                {t('footer.newList')}
              </button>
            </div>

            {/* Language Switcher */}
            <div className="flex justify-center" style={{ marginTop: '16px' }}>
              <LanguageSwitcherCompact />
            </div>
          </div>
        )}
      </div>

      {/* Dictate button (hide when sharing) */}
      {!showShareView && <DictateButton onTranscription={handleDictation} />}

      {/* Save as Template Modal */}
      {showTemplateModal && (
        <SaveAsTemplateModal
          listId={listId}
          listTitle={list?.title || null}
          listTheme={list?.theme || null}
          itemCount={items.length}
          onClose={() => setShowTemplateModal(false)}
        />
      )}
    </div>
  );
}
