'use client';

import { useState, useRef, useEffect } from 'react';

interface ListTitleProps {
  title: string | null;
  onUpdate: (title: string) => Promise<void>;
  isAutoGenerated?: boolean;
}

export function ListTitle({ title, onUpdate, isAutoGenerated = false }: ListTitleProps) {
  const [isEditing, setIsEditing] = useState(false);
  const [value, setValue] = useState(title || '');
  const [showFadeIn, setShowFadeIn] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    setValue(title || '');
  }, [title]);

  // Trigger fade-in animation when auto-generated
  useEffect(() => {
    if (isAutoGenerated && title) {
      setShowFadeIn(true);
      const timer = setTimeout(() => setShowFadeIn(false), 1000);
      return () => clearTimeout(timer);
    }
  }, [isAutoGenerated, title]);

  useEffect(() => {
    if (isEditing && inputRef.current) {
      inputRef.current.focus();
      inputRef.current.select();
    }
  }, [isEditing]);

  const handleSubmit = async () => {
    const trimmed = value.trim();
    if (trimmed !== title) {
      await onUpdate(trimmed);
    }
    setIsEditing(false);
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') {
      handleSubmit();
    } else if (e.key === 'Escape') {
      setValue(title || '');
      setIsEditing(false);
    }
  };

  if (isEditing) {
    return (
      <input
        ref={inputRef}
        type="text"
        value={value}
        onChange={(e) => setValue(e.target.value)}
        onBlur={handleSubmit}
        onKeyDown={handleKeyDown}
        placeholder="Untitled List"
        className="text-2xl font-semibold bg-transparent border-none outline-none w-full"
        style={{ color: 'var(--text-primary)' }}
      />
    );
  }

  return (
    <h1
      onClick={() => setIsEditing(true)}
      className={`text-2xl font-semibold cursor-pointer transition-all duration-500 ${showFadeIn ? 'animate-fade-in' : ''}`}
      style={{
        color: 'var(--text-primary)',
        opacity: showFadeIn ? 1 : undefined,
      }}
      onMouseEnter={(e) => e.currentTarget.style.color = 'var(--text-secondary)'}
      onMouseLeave={(e) => e.currentTarget.style.color = 'var(--text-primary)'}
    >
      {title || 'Untitled List'}
    </h1>
  );
}
